### ISSUE TITLE
ユーザーの認証ネットワークの変更がエラーになる

### ISSUE THREAD

**Issue by raccy** [kue-ipc/ikamail#44]
ユーザーの設定で「認証ネットワーク」を別のネットワークや「なし」に変更しようとしてもエラーになり変更できない。

別のネットワークへの変更

```
I, [2022-04-06T08:41:14.951579 #1709]  INFO -- : [9b85db2b-6305-4b5a-abcf-ee22130bea5a] Started PATCH "/users/3427" for 192.168.122.19 at 2022-04-06 08:41:14 +0900
I, [2022-04-06T08:41:14.952446 #1709]  INFO -- : [9b85db2b-6305-4b5a-abcf-ee22130bea5a] Processing by UsersController#update as HTML
I, [2022-04-06T08:41:14.952519 #1709]  INFO -- : [9b85db2b-6305-4b5a-abcf-ee22130bea5a]   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"auth_network_id"=>"862"}, "commit"=>"変更", "id"=>"3427"}
I, [2022-04-06T08:41:14.965707 #1709]  INFO -- : [9b85db2b-6305-4b5a-abcf-ee22130bea5a] Completed 500 Internal Server Error in 13ms (ActiveRecord: 3.0ms | Allocations: 3989)
F, [2022-04-06T08:41:14.966481 #1709] FATAL -- : [9b85db2b-6305-4b5a-abcf-ee22130bea5a]   
[9b85db2b-6305-4b5a-abcf-ee22130bea5a] ActiveRecord::ReadOnlyRecord (Assignment is marked as readonly):
[9b85db2b-6305-4b5a-abcf-ee22130bea5a]   
[9b85db2b-6305-4b5a-abcf-ee22130bea5a] app/models/user.rb:164:in `block in auth_network='
[9b85db2b-6305-4b5a-abcf-ee22130bea5a] app/models/user.rb:163:in `auth_network='
[9b85db2b-6305-4b5a-abcf-ee22130bea5a] app/models/user.rb:146:in `auth_network_id='
[9b85db2b-6305-4b5a-abcf-ee22130bea5a] app/controllers/users_controller.rb:55:in `block in update'
[9b85db2b-6305-4b5a-abcf-ee22130bea5a] app/controllers/users_controller.rb:54:in `update'
```

「なし」に変更

```
I, [2022-04-06T08:43:02.801299 #1709]  INFO -- : [6ed02e74-6382-40b5-bf00-bcbe4fa965bd] Started PATCH "/users/3427" for 192.168.122.19 at 2022-04-06 08:43:02 +0900
I, [2022-04-06T08:43:02.802171 #1709]  INFO -- : [6ed02e74-6382-40b5-bf00-bcbe4fa965bd] Processing by UsersController#update as HTML
I, [2022-04-06T08:43:02.802239 #1709]  INFO -- : [6ed02e74-6382-40b5-bf00-bcbe4fa965bd]   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"auth_network_id"=>""}, "commit"=>"変更", "id"=>"3427"}
I, [2022-04-06T08:43:02.812046 #1709]  INFO -- : [6ed02e74-6382-40b5-bf00-bcbe4fa965bd] Completed 404 Not Found in 10ms (ActiveRecord: 2.5ms | Allocations: 2892)
F, [2022-04-06T08:43:02.812764 #1709] FATAL -- : [6ed02e74-6382-40b5-bf00-bcbe4fa965bd]   
[6ed02e74-6382-40b5-bf00-bcbe4fa965bd] ActiveRecord::RecordNotFound (Couldn't find Network with 'id'=):
[6ed02e74-6382-40b5-bf00-bcbe4fa965bd]   
[6ed02e74-6382-40b5-bf00-bcbe4fa965bd] app/models/user.rb:146:in `auth_network_id='
[6ed02e74-6382-40b5-bf00-bcbe4fa965bd] app/controllers/users_controller.rb:55:in `block in update'
[6ed02e74-6382-40b5-bf00-bcbe4fa965bd] app/controllers/users_controller.rb:54:in `update'
```

**Comment by raccy** [comment]
Issueを投げるところを間違えた。
